default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Estimate & Invoice Pro.xcodeproj")
    build_app(
      scheme: "Estimate & Invoice Pro",
      export_method: "app-store",
      xcargs: "-destination 'generic/platform=iOS'"
    )
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end